version: '3'

services:

  backend:
    build: ./backend
    image: archipelag_backend
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /code/archipelag
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./backend/code:/code
    env_file: .env

  postgres:
    image: postgres:9.4
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=archipelag
      - POSTGRES_USER=archipelag
      - POSTGRES_DB=archipelag
      - PGPASSWORD=archipelag

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env

  maildump:
    image: ball6847/maildump

  celery:
    image: archipelag_backend
    command: celery -A archipelag worker -l info
    env_file: .env
    working_dir: /code/archipelag
    tty: true
    stdin_open: true
    volumes:
      - ./backend/code:/code


volumes:
  postgres-data:
