# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0002_auto_20171214_2214'),
        ('message', '0003_auto_20171126_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.NgoUser')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
