# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0002_auto_20171214_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SH', 'SHARE'), ('AP', 'ADMIN PROMOTE'), ('RI', 'REGISTER FROM INVITATION'), ('R', 'REGISTER')], default='SH', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id_connected_object', models.PositiveIntegerField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.NgoUser')),
            ],
        ),
    ]
