# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='id_connected_object',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
