# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_auto_20171214_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouser',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
