# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_auto_20180204_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngouser',
            old_name='name',
            new_name='organisation',
        ),
    ]
