# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20171125_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
