# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20171125_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='url',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
