# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180104_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='url',
            new_name='description',
        ),
    ]
