# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20171218_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
