# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180110_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='description',
        ),
    ]
