# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_market_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
