# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20180213_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
