# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20180221_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
